version: '3.8'

services:
  mongodb:
    image: mongo:6
    container_name: mongodb-prod
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - clothing-store-network
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
    healthcheck:
      test: [ "CMD", "mongosh", "-u", "${DB_USER}", "-p", "${DB_PASSWORD}", "--authenticationDatabase", "admin", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: ./backend
    container_name: cloth-backend
    env_file: ./backend/.env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
    ports:
      - "4000:4000"
    networks:
      - clothing-store-network
    depends_on:
      mongodb:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G

  frontend:
    build:
      context: ./cloudrep-frontend
      dockerfile: Dockerfile
    container_name: cloth-frontend
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - ./cloudrep-frontend:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:4000
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - clothing-store-network

volumes:
  mongodb_data:


networks:
  clothing-store-network:
    driver: bridge
