import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./../globals.css";
import NavBar from "@/components/Pages/Common/NavBar";
import Footer from "@/components/Pages/Common/Footer";
import ReduxProvider from "@/lib/provider";
import UserLoader from "@/components/UserLoader";
import SidebarDashboard from "@/components/Pages/Common/SidebarDashboard";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "CloudRep clothing Store",
  description: "Generated by create next app",
  icons: {
    icon: [{ url: "/favicons.ico", sizes: "any" }],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        <ReduxProvider>
          <UserLoader />
          <NavBar />
          <div className="min-h-screen bg-gray-50 flex">
            <SidebarDashboard />
            <div className="flex-1 p-8">{children}</div>
          </div>
          <Footer />
        </ReduxProvider>
      </body>
    </html>
  );
}
